name:                Del2
version:             0.1.0.0
github:              "githubuser/Del2"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  Del2-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Del2

tests:
  Del2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Del2

dependencies: 
  - base
  - servant
  - servant-server
  - servant-options
  - servant-client
  - http-client
  - transformers
  - aeson
  - wai
  - wai-cors
  - warp
  - open-browser