name:                VisAST
version:             0.1.0.0
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"


dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  VisAST-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - VisAST

  TestParser-exe:
    main:               TestParser.hs
    source-dirs:        app 
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is TestParser
    dependencies:
    - VisAST

tests:
  VisAST-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - VisAST

dependencies: 
  - base
  - servant
  - servant-server
  - servant-options
  - servant-client
  - http-client
  - transformers
  - aeson
  - wai
  - wai-cors
  - warp
  - open-browser